[project]
name = "genai4bio-project"
version = "0.1.0"
description = "Cell type-specific gene expression prediction integrating AlphaGenome with single-cell data"
requires-python = ">=3.10,<3.12" # requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9",
    "alphagenome-research",
    "dotenv>=0.9.9",
    "google-cloud-storage>=2.0",
    "pyarrow>=23.0.1",
    "requests>=2.32",
    "scanpy>=1.12"
]

[tool.uv.sources]
alphagenome-research = { git = "https://github.com/google-deepmind/alphagenome_research.git" }

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
